services:
  mongo:
    image: mongo
    restart: always
    container_name: testable_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - "27018:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 3s
      timeout: 3s
      retries: 3
  nats:
    container_name: nats-server-test
    image: nats
    ports:
      - "4223:4222"
