services:
  mongo:
    image: mongo:7.0.14
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - db-data:/data/db

  app:
    image: iot-management-device
    container_name: iot-management-device
    build:
      context: .
      dockerfile: iot-management-device/Dockerfile-iot
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  gateway:
    image: gateway
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile-gateway
    env_file:
      - .env
    ports:
      - "8080:8080"

  nats:
    container_name: nats-server
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  db-data:
