spring:
  application:
    name: iot_management_device
  data:
    mongodb:
      uri: mongodb://localhost:27018/testDB?replicaSet=rs0&authSource=admin

  main:
    web-application-type: reactive
  security:
    public:
      endpoints: /v3/api-docs/**,/swagger-ui/**,/users/**,/error,/auth/**,/devices/**

mongock:
  migration-scan-package: com.example.iotmanagementdevice.mongock.changelogs

jwt:
  expiration: 300000000
  secret: P23wHHMjD4anZ+9DlEYXmcDf481v0Ptmcq9LzVtBcLjR79e5wD1MyEZgOI2a8Cw9

nats.uri: ${NATS_URI}
