name: Update Check Run

on:
  workflow_dispatch:
    inputs:
      target-repo:
        description: 'Target repository name'
        required: true

permissions:
  actions: write
  checks: write
  contents: read

jobs:
  update-check-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update check run
        uses: ./.github/actions/update-check-run
        with:
          target-repo: ${{ inputs.target-repo }}
          check-run-name: Test Coverage
          conclusion: success
          title: No title
          summary: No summary
          text: Some text
